### PR TITLE
fix nightly tests

### PR DESCRIPTION
**Pull request by Dr-Irv**
Had failures as of 12/18, so this fixes them.

### CODE REVIEW

**Review by twoertwein — APPROVED** [review]
The mac failures might be a pandas bug (or an issue of a pandas dependency)?

**Comment by Dr-Irv** [comment]
> The mac failures might be a pandas bug (or an issue of a pandas dependency)?

Really strange, because the runs done less than an hour succeeded:
https://github.com/pandas-dev/pandas-stubs/actions/runs/7250869698/

Maybe something funky with Github?

**Comment by twoertwein** [comment]
> he runs done less than an hour succeeded

Happy to merge anyway :)

**Comment by Dr-Irv** [comment]
> > he runs done less than an hour succeeded
> 
> Happy to merge anyway :)

I reran the two failed jobs and they succeeded:  https://github.com/pandas-dev/pandas-stubs/actions/runs/7251171162

**Pull request merged**
