### PR TITLE
Restore nightly CI build due to new pandas version (3.0.0)

### LINKED ISSUE #973: Restore nightly CI build due to new pandas version (3.0.0)
**Describe the bug**
Due to many new deprecations in pandas 3.0.0, the nightly build involving the new version of pandas is failing.

**To Reproduce**
`poetry run poe test_all --nightly`
Also see the Actions tab in the GitHub repo.

**Please complete the following information:**
 - OS: MacOS
 - OS Version: 14.5
 - python version: 3.12.4
 - version of type checker: 1.1.373
 - version of installed `pandas-stubs`: v2.2.2.240807

### PR DESCRIPTION
**Pull request by loicdiridollou**
- [x] Closes #973
- [x] Tests added: Please use `assert_type()` to assert the type of any return value

We can probably be a little more elegant in some of the `pytest_warn_bounds` where we define a variable then redefine it the line below if we are dealing with pandas 3.0.0, open to suggestions.

### CODE REVIEW

**Comment by Dr-Irv** [comment]
> We can probably be a little more elegant in some of the `pytest_warn_bounds` where we define a variable then redefine it the line below if we are dealing with pandas 3.0.0, open to suggestions.

I'm open to better ways of doing the tests here, but will accept this PR as is.

**Review by Dr-Irv — APPROVED** [review]
thanks @loicdiridollou

**Comment by Dr-Irv** [comment]
@loicdiridollou looks like the fix for `test_versions()` didn't work.  See https://github.com/pandas-dev/pandas-stubs/actions/runs/10289869197/job/28478532479

**Comment by loicdiridollou** [comment]
Arghh I thought I had it fixed, sorry for that let me investigate and fix.

**Comment by loicdiridollou** [comment]
I was able to have a running build on my own repo, see https://github.com/loicdiridollou/pandas-stubs/actions/runs/10290769879/job/28481506269.
The PR is here (https://github.com/pandas-dev/pandas-stubs/pull/975), the issue was that pandas>=3.0.0 does not seem to rely on `distutils` anymore so the warning was never raised to the user

**Pull request merged**
