### PR TITLE
CI: run nightly tests only on main

### PR DESCRIPTION
**Pull request by twoertwein**
xref #568

### CODE REVIEW

**Comment by twoertwein** [comment]
I still got an email from the error on my fork. I think there might be repository-wide settings to either disable running fork workflows or at least skipping the optional nightly workflow for forks.

**Comment by twoertwein** [comment]
I don't have permissions to change the repository settings. Disabling workflows for forks might also help the workflows here to start earlier (assuming they share the same queue).

**Comment by Dr-Irv** [comment]
> I don't have permissions to change the repository settings. Disabling workflows for forks might also help the workflows here to start earlier (assuming they share the same queue).

I've given you Admin permissions on `pandas-stubs` so now you can change the settings.  Let me know if I should approve and merge before or after you change the settings.

**Review by Dr-Irv — APPROVED** [review]
I'm approving, but not merging.  Will await for merging once you decide if I should merge before or after you make the changes in settings.

**Comment by twoertwein** [comment]
> edit: https://github.com/orgs/community/discussions/26704#discussioncomment-3252979

I realized that the above link does not allow disabling actions for forks (its only actions on for everything or nothing). Feel free to remove the admin permissions for me again. I made no settings changes.

I think with the current version, the CI will still run for forks but only if people push to `main` of their fork (haven't tested it). At the very least, the CI is not run for my [fork](https://github.com/twoertwein/pandas-stubs/tree/ci_nightly) for this PR.

could add `if: ${{ github.repository == 'pandas-dev/pandas-stubs' }}` to all jobs to also ensure that the CI isn't run on forks/main. Pandas doesn't seem to do that.

**Comment by Dr-Irv** [comment]
> Feel free to remove the admin permissions for me again. I made no settings changes.

I've removed them, but thanks for letting me know that no changes were made.

> 
> I think with the current version, the CI will still run for forks but only if people push to `main` of their fork (haven't tested it). At the very least, the CI is not run for my [fork](https://github.com/twoertwein/pandas-stubs/tree/ci_nightly) for this PR.

Let's see what happens after I merge.
> 
> could add `if: ${{ github.repository == 'pandas-dev/pandas-stubs' }}` to all jobs to also ensure that the CI isn't run on forks/main. Pandas doesn't seem to do that.

I'm not going to worry too much about what happens with people's personal forks of the repo.  At least for me, if I'm creating a PR, I just push to the new branch and let the actions run.  If everything passes, I'll create the PR.  If not, I fix before doing the PR.

**Comment by Dr-Irv** [comment]
> > I think with the current version, the CI will still run for forks but only if people push to `main` of their fork (haven't tested it). At the very least, the CI is not run for my [fork](https://github.com/twoertwein/pandas-stubs/tree/ci_nightly) for this PR.
> 
> Let's see what happens after I merge.

So it's actually quite nice.  It seems to create 2 separate actions for `main` - one is the set we care about, and the second is the nightly ones.

**Pull request merged**
