### PR TITLE
MAINT: Show python info on Windows

### PR DESCRIPTION
**Pull request by bashtage**
- [ ] Closes #xxxx (Replace xxxx with the Github issue number)
- [ ] Tests added: Please use `assert_type()` to assert the type of any return value

### CODE REVIEW

**Comment by bashtage** [comment]
@Dr-Irv @twoertwein I think it would be good to get this in - it might help diagnose cache issues since we could see if the location of the virtualenv was changing, and it somehow windows was missing the location of the venv python.exe.

**Review by Dr-Irv — APPROVED** [review]
Thanks @bashtage

**Comment by Dr-Irv** [comment]
Might be worth trying this without the pinning of the poetry version.  I think it worked because it picked up an "old" cache.

**Comment by twoertwein** [comment]
Might also be good to make the cache key dependent on `poetry run python --version` instead of using the string from the matrix setup.

**Pull request merged**
