### PR TITLE
gh-514 Added `ExtensionDtype` for `is_*_dtype` functions

### LINKED ISSUE #514: `is_*_dtype` functions don't accept extension dtypes
The [`_ArrayOrDtype`](https://github.com/pandas-dev/pandas-stubs/blob/db3b883dbe8d22863c8aca37c89431afce3b57e2/pandas-stubs/core/dtypes/common.pyi#L31-L33) alias doesn't include `ExtensionDtype`, which I believe all the `is_*_dtype` functions accept.

### PR DESCRIPTION
**Pull request by ramvikrams**
- [x] Closes #514 
- [x] Tests added: Please use `assert_type()` to assert the type of any return value

### CODE REVIEW

**Review by Dr-Irv — CHANGES_REQUESTED** [review]
For each of the commented out lines, can you add at the end the reference to the pandas Github issue, e.g.:
```python
# check(assert_type(api.is_object_dtype(ExtensionDtype), bool), bool)   pandas GH 50923
```

**Comment by ramvikrams** [comment]
> For each of the commented out lines, can you add at the end the reference to the pandas Github issue, e.g.:

added the reference

**Review by Dr-Irv — APPROVED** [review]
thanks @ramvikrams

**Comment by ramvikrams** [comment]
> thanks @ramvikrams

thanks sir

**Pull request merged**
