### PR TITLE
ENH: Improve Arrays

### PR DESCRIPTION
**Pull request by bashtage**
- [X] Tests added: Please use `assert_type()` to assert the type of any return value

### CODE REVIEW

**Comment by bashtage** [comment]
Not ready for review.  Splitting #383 into dtypes, arrays and scalars.

**Comment by Dr-Irv** [comment]
@bashtage checking on status of this

**Comment by bashtage** [comment]
Want to get the interval on in first.  Been busy of late but all will be revived.

**Comment by twoertwein** [comment]
I was hoping I can simply rebase, fix the CI, and compare it to the documentation&implementation to get it closer to being merged (naive me). I got the first two done but there is much more work left (the pandas implementation changed quite a bit). I will probably not continue this work as I don't use the Arrays directly and many of them are still marked as experimental.

**Comment by bashtage** [comment]
Pretty stale.  I'll see if it can be revived.

**Comment by twoertwein** [comment]
Closing it so that it is a tiny bit easier to focus on current PRs. Feel free to re-open.

**Pull request closed without merging**
