### PR TITLE
Broaden read csv param types

### LINKED ISSUE #605: usecols keyword argument of pd.read_csv says it expects list[str] but the documentation says otherwise
**Describe the bug**
`usecols` keyword argument of `pd.read_csv` says it expects `list[str]` but the documentation says otherwise:

image

Documentation (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html):
> usecols list-like or callable, optional Return a subset of the columns. If list-like, all elements must either be positional (i.e. integer indices into the document columns) or strings that correspond to column names provided either by the user in names or inferred from the document header row(s). If names are given, the document header row(s) are not taken into account. For example, a valid list-like usecols parameter would be [0, 1, 2] or ['foo', 'bar', 'baz']. Element order is ignored, so usecols=[0, 1] is the same as [1, 0]. To instantiate a DataFrame from data with element order preserved use pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']] for columns in ['foo', 'bar'] order or pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']] for ['bar', 'foo'] order.
> 
> If callable, the callable function will be evaluated against the column names, returning names where the callable function evaluates to True. An example of a valid callable argument would be lambda x: x.upper() in ['AAA', 'BBB', 'DDD']. Using this parameter results in much faster parsing time and lower memory usage.

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
`import pandas as pd; path_to_csv = "mycsv.csv"; df_db = pd.read_csv(path_to_csv, usecols=[0])`
2. Indicate which type checker you are using (`mypy` or  `pyright`). PyCharm default type-checker, I haven't checked `mypy`.
3. Show the error message received from that type checker while checking your example.
image

**Please complete the following information:**
 - OS: Windows
 - OS Version 11
 - python version `3.11.1`
 - version of type checker `mypy 1.1.1`
 - version of installed `pandas-stubs` `pandas-stubs 1.5.3.230321`

**Additional context**
[Realted to this SO post.](https://stackoverflow.com/questions/75878435/usecols-keyword-argument-of-pd-read-csv-says-it-expects-liststr-but-the-docume)

### LINKED ISSUE #623: names parameter of pd.read_csv restricted to list[str] even though the valid types are much broader
**Describe the bug**
Closely related to #605

The stubs for the `read_csv` function, in `pandas-stubs/io/parsers/readers.pyi`, type hint the 'names' param as `list[str]`, even though a much wider range of types is usable here. The [pandas docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) say:

> names: array-like, optional
List of column names to use. If the file contains a header row, then you should explicitly pass header=0 to override the column names. Duplicates in this list are not allowed.

And the [pandas code](https://github.com/pandas-dev/pandas/blob/0ba82890fb398a7afc2d6a1b83e31fa3b33fceae/pandas/io/parsers/readers.py#L616) suggests a `Sequence[Hashable]` is allowed.

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.

```python
import pandas as pd

pd.read_csv("test.csv", names=("first", "second", "third"))
pd.read_csv("test.csv", names=(7, 8, 9))
# MultiIndex - although unclear to me if this is part of the 'public api' and therefore something pandas-stubs wants to cover
pd.read_csv("test.csv", names=(("head", "first"), ("tail", "second"), ("tail", "third")))
```

contents of `test.csv` was just:

```csv
1,2,3
4,5,6
```

3. mypy
4. Show the error message received from that type checker while checking your example.

abridged, because there's lots of output about possible overload variants:

```console
test_read_csv.py:3: error: No overload variant of "read_csv" matches argument types "str", "Tuple[str, str, str]"  [call-overload]
...
test_read_csv.py:4: error: No overload variant of "read_csv" matches argument types "str", "Tuple[int, int, int]"  [call-overload]
...
test_read_csv.py:6: error: No overload variant of "read_csv" matches argument types "str", "Tuple[Tuple[str, str], Tuple[str, str], Tuple[str, str]]"  [call-overload]
```

<details><summary>Full error</summary>

```console
test_read_csv.py:3: error: No overload variant of "read_csv" matches argument types "str", "Tuple[str, str, str]"  [call-overload]
test_read_csv.py:3: note: Possible overload variants:
test_read_csv.py:3: note:     def read_csv(filepath_or_buffer: Union[Union[str, PathLike[str]], ReadCsvBuffer[bytes], ReadCsvBuffer[str]], *, sep: Optional[str] = ..., delimiter: Optional[str] = ..., header: Union[int, Sequence[int], Literal['infer'], None] = ..., names: Optional[List[str]] = ..., index_col: Union[int, str, Sequence[Union[str, int]], Literal[False], None] = ..., usecols: Union[List[str], Tuple[str, ...], Sequence[int], Series[Any], Index, ndarray[Any, dtype[Any]], Callable[[str], bool], None] = ..., dtype: Union[Union[Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]], Dict[Any, Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]]]], defaultdict[Any, Any], None] = ..., engine: Optional[Literal['c', 'python', 'pyarrow', 'python-fwf']] = ..., converters: Union[Mapping[Union[int, str], Callable[[str], Any]], Mapping[int, Callable[[str], Any]], Mapping[str, Callable[[str], Any]], None] = ..., true_values: List[str] = ..., false_values: List[str] = ..., skipinitialspace: bool = ..., skiprows: Union[int, Sequence[int], Callable[[int], bool]] = ..., skipfooter: int = ..., nrows: Optional[int] = ..., na_values: Union[Sequence[str], Mapping[str, Sequence[str]]] = ..., keep_default_na: bool = ..., na_filter: bool = ..., verbose: bool = ..., skip_blank_lines: bool = ..., parse_dates: Union[bool, List[int], List[str], Sequence[Sequence[int]], Mapping[str, Sequence[Union[int, str]]]] = ..., infer_datetime_format: bool = ..., keep_date_col: bool = ..., date_parser: Callable[..., Any] = ..., dayfirst: bool = ..., cache_dates: bool = ..., iterator: Literal[True], chunksize: Optional[int] = ..., compression: Union[None, Dict[str, Any], Literal['infer', 'gzip', 'bz2', 'zip', 'xz', 'zstd']] = ..., thousands: Optional[str] = ..., decimal: str = ..., lineterminator: Optional[str] = ..., quotechar: str = ..., quoting: Literal[0, 1, 2, 3] = ..., doublequote: bool = ..., escapechar: Optional[str] = ..., comment: Optional[str] = ..., encoding: Optional[str] = ..., encoding_errors: Optional[str] = ..., dialect: Union[str, Dialect] = ..., on_bad_lines: Union[Callable[[List[str]], Optional[List[str]]], Literal['error', 'warn', 'skip']] = ..., delim_whitespace: bool = ..., low_memory: bool = ..., memory_map: bool = ..., float_precision: Optional[Literal['high', 'legacy', 'round_trip']] = ..., storage_options: Optional[Optional[Dict[str, Any]]] = ...) -> TextFileReader
test_read_csv.py:3: note:     def read_csv(filepath_or_buffer: Union[Union[str, PathLike[str]], ReadCsvBuffer[bytes], ReadCsvBuffer[str]], *, sep: Optional[str] = ..., delimiter: Optional[str] = ..., header: Union[int, Sequence[int], Literal['infer'], None] = ..., names: Optional[List[str]] = ..., index_col: Union[int, str, Sequence[Union[str, int]], Literal[False], None] = ..., usecols: Union[List[str], Tuple[str, ...], Sequence[int], Series[Any], Index, ndarray[Any, dtype[Any]], Callable[[str], bool], None] = ..., dtype: Union[Union[Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]], Dict[Any, Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]]]], defaultdict[Any, Any], None] = ..., engine: Optional[Literal['c', 'python', 'pyarrow', 'python-fwf']] = ..., converters: Union[Mapping[Union[int, str], Callable[[str], Any]], Mapping[int, Callable[[str], Any]], Mapping[str, Callable[[str], Any]], None] = ..., true_values: List[str] = ..., false_values: List[str] = ..., skipinitialspace: bool = ..., skiprows: Union[int, Sequence[int], Callable[[int], bool]] = ..., skipfooter: int = ..., nrows: Optional[int] = ..., na_values: Union[Sequence[str], Mapping[str, Sequence[str]]] = ..., keep_default_na: bool = ..., na_filter: bool = ..., verbose: bool = ..., skip_blank_lines: bool = ..., parse_dates: Union[bool, List[int], List[str], Sequence[Sequence[int]], Mapping[str, Sequence[Union[int, str]]]] = ..., infer_datetime_format: bool = ..., keep_date_col: bool = ..., date_parser: Callable[..., Any] = ..., dayfirst: bool = ..., cache_dates: bool = ..., iterator: bool = ..., chunksize: int, compression: Union[None, Dict[str, Any], Literal['infer', 'gzip', 'bz2', 'zip', 'xz', 'zstd']] = ..., thousands: Optional[str] = ..., decimal: str = ..., lineterminator: Optional[str] = ..., quotechar: str = ..., quoting: Literal[0, 1, 2, 3] = ..., doublequote: bool = ..., escapechar: Optional[str] = ..., comment: Optional[str] = ..., encoding: Optional[str] = ..., encoding_errors: Optional[str] = ..., dialect: Union[str, Dialect] = ..., on_bad_lines: Union[Callable[[List[str]], Optional[List[str]]], Literal['error', 'warn', 'skip']] = ..., delim_whitespace: bool = ..., low_memory: bool = ..., memory_map: bool = ..., float_precision: Optional[Literal['high', 'legacy', 'round_trip']] = ..., storage_options: Optional[Optional[Dict[str, Any]]] = ...) -> TextFileReader
test_read_csv.py:3: note:     def read_csv(filepath_or_buffer: Union[Union[str, PathLike[str]], ReadCsvBuffer[bytes], ReadCsvBuffer[str]], *, sep: Optional[str] = ..., delimiter: Optional[str] = ..., header: Union[int, Sequence[int], Literal['infer'], None] = ..., names: Optional[List[str]] = ..., index_col: Union[int, str, Sequence[Union[str, int]], Literal[False], None] = ..., usecols: Union[List[str], Tuple[str, ...], Sequence[int], Series[Any], Index, ndarray[Any, dtype[Any]], Callable[[str], bool], None] = ..., dtype: Union[Union[Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]], Dict[Any, Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]]]], defaultdict[Any, Any], None] = ..., engine: Optional[Literal['c', 'python', 'pyarrow', 'python-fwf']] = ..., converters: Union[Mapping[Union[int, str], Callable[[str], Any]], Mapping[int, Callable[[str], Any]], Mapping[str, Callable[[str], Any]], None] = ..., true_values: List[str] = ..., false_values: List[str] = ..., skipinitialspace: bool = ..., skiprows: Union[int, Sequence[int], Callable[[int], bool]] = ..., skipfooter: int = ..., nrows: Optional[int] = ..., na_values: Union[Sequence[str], Mapping[str, Sequence[str]]] = ..., keep_default_na: bool = ..., na_filter: bool = ..., verbose: bool = ..., skip_blank_lines: bool = ..., parse_dates: Union[bool, List[int], List[str], Sequence[Sequence[int]], Mapping[str, Sequence[Union[int, str]]]] = ..., infer_datetime_format: bool = ..., keep_date_col: bool = ..., date_parser: Callable[..., Any] = ..., dayfirst: bool = ..., cache_dates: bool = ..., iterator: Literal[False] = ..., chunksize: None = ..., compression: Union[None, Dict[str, Any], Literal['infer', 'gzip', 'bz2', 'zip', 'xz', 'zstd']] = ..., thousands: Optional[str] = ..., decimal: str = ..., lineterminator: Optional[str] = ..., quotechar: str = ..., quoting: Literal[0, 1, 2, 3] = ..., doublequote: bool = ..., escapechar: Optional[str] = ..., comment: Optional[str] = ..., encoding: Optional[str] = ..., encoding_errors: Optional[str] = ..., dialect: Union[str, Dialect] = ..., on_bad_lines: Union[Callable[[List[str]], Optional[List[str]]], Literal['error', 'warn', 'skip']] = ..., delim_whitespace: bool = ..., low_memory: bool = ..., memory_map: bool = ..., float_precision: Optional[Literal['high', 'legacy', 'round_trip']] = ..., storage_options: Optional[Optional[Dict[str, Any]]] = ...) -> DataFrame
test_read_csv.py:4: error: No overload variant of "read_csv" matches argument types "str", "Tuple[int, int, int]"  [call-overload]
test_read_csv.py:4: note: Possible overload variants:
test_read_csv.py:4: note:     def read_csv(filepath_or_buffer: Union[Union[str, PathLike[str]], ReadCsvBuffer[bytes], ReadCsvBuffer[str]], *, sep: Optional[str] = ..., delimiter: Optional[str] = ..., header: Union[int, Sequence[int], Literal['infer'], None] = ..., names: Optional[List[str]] = ..., index_col: Union[int, str, Sequence[Union[str, int]], Literal[False], None] = ..., usecols: Union[List[str], Tuple[str, ...], Sequence[int], Series[Any], Index, ndarray[Any, dtype[Any]], Callable[[str], bool], None] = ..., dtype: Union[Union[Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]], Dict[Any, Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]]]], defaultdict[Any, Any], None] = ..., engine: Optional[Literal['c', 'python', 'pyarrow', 'python-fwf']] = ..., converters: Union[Mapping[Union[int, str], Callable[[str], Any]], Mapping[int, Callable[[str], Any]], Mapping[str, Callable[[str], Any]], None] = ..., true_values: List[str] = ..., false_values: List[str] = ..., skipinitialspace: bool = ..., skiprows: Union[int, Sequence[int], Callable[[int], bool]] = ..., skipfooter: int = ..., nrows: Optional[int] = ..., na_values: Union[Sequence[str], Mapping[str, Sequence[str]]] = ..., keep_default_na: bool = ..., na_filter: bool = ..., verbose: bool = ..., skip_blank_lines: bool = ..., parse_dates: Union[bool, List[int], List[str], Sequence[Sequence[int]], Mapping[str, Sequence[Union[int, str]]]] = ..., infer_datetime_format: bool = ..., keep_date_col: bool = ..., date_parser: Callable[..., Any] = ..., dayfirst: bool = ..., cache_dates: bool = ..., iterator: Literal[True], chunksize: Optional[int] = ..., compression: Union[None, Dict[str, Any], Literal['infer', 'gzip', 'bz2', 'zip', 'xz', 'zstd']] = ..., thousands: Optional[str] = ..., decimal: str = ..., lineterminator: Optional[str] = ..., quotechar: str = ..., quoting: Literal[0, 1, 2, 3] = ..., doublequote: bool = ..., escapechar: Optional[str] = ..., comment: Optional[str] = ..., encoding: Optional[str] = ..., encoding_errors: Optional[str] = ..., dialect: Union[str, Dialect] = ..., on_bad_lines: Union[Callable[[List[str]], Optional[List[str]]], Literal['error', 'warn', 'skip']] = ..., delim_whitespace: bool = ..., low_memory: bool = ..., memory_map: bool = ..., float_precision: Optional[Literal['high', 'legacy', 'round_trip']] = ..., storage_options: Optional[Optional[Dict[str, Any]]] = ...) -> TextFileReader
test_read_csv.py:4: note:     def read_csv(filepath_or_buffer: Union[Union[str, PathLike[str]], ReadCsvBuffer[bytes], ReadCsvBuffer[str]], *, sep: Optional[str] = ..., delimiter: Optional[str] = ..., header: Union[int, Sequence[int], Literal['infer'], None] = ..., names: Optional[List[str]] = ..., index_col: Union[int, str, Sequence[Union[str, int]], Literal[False], None] = ..., usecols: Union[List[str], Tuple[str, ...], Sequence[int], Series[Any], Index, ndarray[Any, dtype[Any]], Callable[[str], bool], None] = ..., dtype: Union[Union[Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]], Dict[Any, Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]]]], defaultdict[Any, Any], None] = ..., engine: Optional[Literal['c', 'python', 'pyarrow', 'python-fwf']] = ..., converters: Union[Mapping[Union[int, str], Callable[[str], Any]], Mapping[int, Callable[[str], Any]], Mapping[str, Callable[[str], Any]], None] = ..., true_values: List[str] = ..., false_values: List[str] = ..., skipinitialspace: bool = ..., skiprows: Union[int, Sequence[int], Callable[[int], bool]] = ..., skipfooter: int = ..., nrows: Optional[int] = ..., na_values: Union[Sequence[str], Mapping[str, Sequence[str]]] = ..., keep_default_na: bool = ..., na_filter: bool = ..., verbose: bool = ..., skip_blank_lines: bool = ..., parse_dates: Union[bool, List[int], List[str], Sequence[Sequence[int]], Mapping[str, Sequence[Union[int, str]]]] = ..., infer_datetime_format: bool = ..., keep_date_col: bool = ..., date_parser: Callable[..., Any] = ..., dayfirst: bool = ..., cache_dates: bool = ..., iterator: bool = ..., chunksize: int, compression: Union[None, Dict[str, Any], Literal['infer', 'gzip', 'bz2', 'zip', 'xz', 'zstd']] = ..., thousands: Optional[str] = ..., decimal: str = ..., lineterminator: Optional[str] = ..., quotechar: str = ..., quoting: Literal[0, 1, 2, 3] = ..., doublequote: bool = ..., escapechar: Optional[str] = ..., comment: Optional[str] = ..., encoding: Optional[str] = ..., encoding_errors: Optional[str] = ..., dialect: Union[str, Dialect] = ..., on_bad_lines: Union[Callable[[List[str]], Optional[List[str]]], Literal['error', 'warn', 'skip']] = ..., delim_whitespace: bool = ..., low_memory: bool = ..., memory_map: bool = ..., float_precision: Optional[Literal['high', 'legacy', 'round_trip']] = ..., storage_options: Optional[Optional[Dict[str, Any]]] = ...) -> TextFileReader
test_read_csv.py:4: note:     def read_csv(filepath_or_buffer: Union[Union[str, PathLike[str]], ReadCsvBuffer[bytes], ReadCsvBuffer[str]], *, sep: Optional[str] = ..., delimiter: Optional[str] = ..., header: Union[int, Sequence[int], Literal['infer'], None] = ..., names: Optional[List[str]] = ..., index_col: Union[int, str, Sequence[Union[str, int]], Literal[False], None] = ..., usecols: Union[List[str], Tuple[str, ...], Sequence[int], Series[Any], Index, ndarray[Any, dtype[Any]], Callable[[str], bool], None] = ..., dtype: Union[Union[Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]], Dict[Any, Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]]]], defaultdict[Any, Any], None] = ..., engine: Optional[Literal['c', 'python', 'pyarrow', 'python-fwf']] = ..., converters: Union[Mapping[Union[int, str], Callable[[str], Any]], Mapping[int, Callable[[str], Any]], Mapping[str, Callable[[str], Any]], None] = ..., true_values: List[str] = ..., false_values: List[str] = ..., skipinitialspace: bool = ..., skiprows: Union[int, Sequence[int], Callable[[int], bool]] = ..., skipfooter: int = ..., nrows: Optional[int] = ..., na_values: Union[Sequence[str], Mapping[str, Sequence[str]]] = ..., keep_default_na: bool = ..., na_filter: bool = ..., verbose: bool = ..., skip_blank_lines: bool = ..., parse_dates: Union[bool, List[int], List[str], Sequence[Sequence[int]], Mapping[str, Sequence[Union[int, str]]]] = ..., infer_datetime_format: bool = ..., keep_date_col: bool = ..., date_parser: Callable[..., Any] = ..., dayfirst: bool = ..., cache_dates: bool = ..., iterator: Literal[False] = ..., chunksize: None = ..., compression: Union[None, Dict[str, Any], Literal['infer', 'gzip', 'bz2', 'zip', 'xz', 'zstd']] = ..., thousands: Optional[str] = ..., decimal: str = ..., lineterminator: Optional[str] = ..., quotechar: str = ..., quoting: Literal[0, 1, 2, 3] = ..., doublequote: bool = ..., escapechar: Optional[str] = ..., comment: Optional[str] = ..., encoding: Optional[str] = ..., encoding_errors: Optional[str] = ..., dialect: Union[str, Dialect] = ..., on_bad_lines: Union[Callable[[List[str]], Optional[List[str]]], Literal['error', 'warn', 'skip']] = ..., delim_whitespace: bool = ..., low_memory: bool = ..., memory_map: bool = ..., float_precision: Optional[Literal['high', 'legacy', 'round_trip']] = ..., storage_options: Optional[Optional[Dict[str, Any]]] = ...) -> DataFrame
test_read_csv.py:6: error: No overload variant of "read_csv" matches argument types "str", "Tuple[Tuple[str, str], Tuple[str, str], Tuple[str, str]]"  [call-overload]
test_read_csv.py:6: note: Possible overload variants:
test_read_csv.py:6: note:     def read_csv(filepath_or_buffer: Union[Union[str, PathLike[str]], ReadCsvBuffer[bytes], ReadCsvBuffer[str]], *, sep: Optional[str] = ..., delimiter: Optional[str] = ..., header: Union[int, Sequence[int], Literal['infer'], None] = ..., names: Optional[List[str]] = ..., index_col: Union[int, str, Sequence[Union[str, int]], Literal[False], None] = ..., usecols: Union[List[str], Tuple[str, ...], Sequence[int], Series[Any], Index, ndarray[Any, dtype[Any]], Callable[[str], bool], None] = ..., dtype: Union[Union[Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]], Dict[Any, Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]]]], defaultdict[Any, Any], None] = ..., engine: Optional[Literal['c', 'python', 'pyarrow', 'python-fwf']] = ..., converters: Union[Mapping[Union[int, str], Callable[[str], Any]], Mapping[int, Callable[[str], Any]], Mapping[str, Callable[[str], Any]], None] = ..., true_values: List[str] = ..., false_values: List[str] = ..., skipinitialspace: bool = ..., skiprows: Union[int, Sequence[int], Callable[[int], bool]] = ..., skipfooter: int = ..., nrows: Optional[int] = ..., na_values: Union[Sequence[str], Mapping[str, Sequence[str]]] = ..., keep_default_na: bool = ..., na_filter: bool = ..., verbose: bool = ..., skip_blank_lines: bool = ..., parse_dates: Union[bool, List[int], List[str], Sequence[Sequence[int]], Mapping[str, Sequence[Union[int, str]]]] = ..., infer_datetime_format: bool = ..., keep_date_col: bool = ..., date_parser: Callable[..., Any] = ..., dayfirst: bool = ..., cache_dates: bool = ..., iterator: Literal[True], chunksize: Optional[int] = ..., compression: Union[None, Dict[str, Any], Literal['infer', 'gzip', 'bz2', 'zip', 'xz', 'zstd']] = ..., thousands: Optional[str] = ..., decimal: str = ..., lineterminator: Optional[str] = ..., quotechar: str = ..., quoting: Literal[0, 1, 2, 3] = ..., doublequote: bool = ..., escapechar: Optional[str] = ..., comment: Optional[str] = ..., encoding: Optional[str] = ..., encoding_errors: Optional[str] = ..., dialect: Union[str, Dialect] = ..., on_bad_lines: Union[Callable[[List[str]], Optional[List[str]]], Literal['error', 'warn', 'skip']] = ..., delim_whitespace: bool = ..., low_memory: bool = ..., memory_map: bool = ..., float_precision: Optional[Literal['high', 'legacy', 'round_trip']] = ..., storage_options: Optional[Optional[Dict[str, Any]]] = ...) -> TextFileReader
test_read_csv.py:6: note:     def read_csv(filepath_or_buffer: Union[Union[str, PathLike[str]], ReadCsvBuffer[bytes], ReadCsvBuffer[str]], *, sep: Optional[str] = ..., delimiter: Optional[str] = ..., header: Union[int, Sequence[int], Literal['infer'], None] = ..., names: Optional[List[str]] = ..., index_col: Union[int, str, Sequence[Union[str, int]], Literal[False], None] = ..., usecols: Union[List[str], Tuple[str, ...], Sequence[int], Series[Any], Index, ndarray[Any, dtype[Any]], Callable[[str], bool], None] = ..., dtype: Union[Union[Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]], Dict[Any, Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]]]], defaultdict[Any, Any], None] = ..., engine: Optional[Literal['c', 'python', 'pyarrow', 'python-fwf']] = ..., converters: Union[Mapping[Union[int, str], Callable[[str], Any]], Mapping[int, Callable[[str], Any]], Mapping[str, Callable[[str], Any]], None] = ..., true_values: List[str] = ..., false_values: List[str] = ..., skipinitialspace: bool = ..., skiprows: Union[int, Sequence[int], Callable[[int], bool]] = ..., skipfooter: int = ..., nrows: Optional[int] = ..., na_values: Union[Sequence[str], Mapping[str, Sequence[str]]] = ..., keep_default_na: bool = ..., na_filter: bool = ..., verbose: bool = ..., skip_blank_lines: bool = ..., parse_dates: Union[bool, List[int], List[str], Sequence[Sequence[int]], Mapping[str, Sequence[Union[int, str]]]] = ..., infer_datetime_format: bool = ..., keep_date_col: bool = ..., date_parser: Callable[..., Any] = ..., dayfirst: bool = ..., cache_dates: bool = ..., iterator: bool = ..., chunksize: int, compression: Union[None, Dict[str, Any], Literal['infer', 'gzip', 'bz2', 'zip', 'xz', 'zstd']] = ..., thousands: Optional[str] = ..., decimal: str = ..., lineterminator: Optional[str] = ..., quotechar: str = ..., quoting: Literal[0, 1, 2, 3] = ..., doublequote: bool = ..., escapechar: Optional[str] = ..., comment: Optional[str] = ..., encoding: Optional[str] = ..., encoding_errors: Optional[str] = ..., dialect: Union[str, Dialect] = ..., on_bad_lines: Union[Callable[[List[str]], Optional[List[str]]], Literal['error', 'warn', 'skip']] = ..., delim_whitespace: bool = ..., low_memory: bool = ..., memory_map: bool = ..., float_precision: Optional[Literal['high', 'legacy', 'round_trip']] = ..., storage_options: Optional[Optional[Dict[str, Any]]] = ...) -> TextFileReader
test_read_csv.py:6: note:     def read_csv(filepath_or_buffer: Union[Union[str, PathLike[str]], ReadCsvBuffer[bytes], ReadCsvBuffer[str]], *, sep: Optional[str] = ..., delimiter: Optional[str] = ..., header: Union[int, Sequence[int], Literal['infer'], None] = ..., names: Optional[List[str]] = ..., index_col: Union[int, str, Sequence[Union[str, int]], Literal[False], None] = ..., usecols: Union[List[str], Tuple[str, ...], Sequence[int], Series[Any], Index, ndarray[Any, dtype[Any]], Callable[[str], bool], None] = ..., dtype: Union[Union[Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]], Dict[Any, Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]]]], defaultdict[Any, Any], None] = ..., engine: Optional[Literal['c', 'python', 'pyarrow', 'python-fwf']] = ..., converters: Union[Mapping[Union[int, str], Callable[[str], Any]], Mapping[int, Callable[[str], Any]], Mapping[str, Callable[[str], Any]], None] = ..., true_values: List[str] = ..., false_values: List[str] = ..., skipinitialspace: bool = ..., skiprows: Union[int, Sequence[int], Callable[[int], bool]] = ..., skipfooter: int = ..., nrows: Optional[int] = ..., na_values: Union[Sequence[str], Mapping[str, Sequence[str]]] = ..., keep_default_na: bool = ..., na_filter: bool = ..., verbose: bool = ..., skip_blank_lines: bool = ..., parse_dates: Union[bool, List[int], List[str], Sequence[Sequence[int]], Mapping[str, Sequence[Union[int, str]]]] = ..., infer_datetime_format: bool = ..., keep_date_col: bool = ..., date_parser: Callable[..., Any] = ..., dayfirst: bool = ..., cache_dates: bool = ..., iterator: Literal[False] = ..., chunksize: None = ..., compression: Union[None, Dict[str, Any], Literal['infer', 'gzip', 'bz2', 'zip', 'xz', 'zstd']] = ..., thousands: Optional[str] = ..., decimal: str = ..., lineterminator: Optional[str] = ..., quotechar: str = ..., quoting: Literal[0, 1, 2, 3] = ..., doublequote: bool = ..., escapechar: Optional[str] = ..., comment: Optional[str] = ..., encoding: Optional[str] = ..., encoding_errors: Optional[str] = ..., dialect: Union[str, Dialect] = ..., on_bad_lines: Union[Callable[[List[str]], Optional[List[str]]], Literal['error', 'warn', 'skip']] = ..., delim_whitespace: bool = ..., low_memory: bool = ..., memory_map: bool = ..., float_precision: Optional[Literal['high', 'legacy', 'round_trip']] = ..., storage_options: Optional[Optional[Dict[str, Any]]] = ...) -> DataFrame
Found 3 errors in 1 file (checked 1 source file)
```

</details> 

**Please complete the following information:**
 - OS: MacOS
 - OS Version: Ventura 13.3 (22E252)
 - python version: 3.10.0
 - version of type checker: mypy 1.1.1 (compiled: yes)
 - version of installed `pandas-stubs`

**Additional context**
I was planning to open a PR for this, but I'm actually unsure what type hint is best. My thought process went:

1. Maybe it can be a `Sequence[Hashable]` like in pandas-dev/pandas.
2. No, it can't because this wouldn't disallow a single string (which errors - `pd.read_csv("test.csv", names="abc")` gives `ValueError: Names should be an ordered collection.`).
3. I can take inspiration from `ListLikeExceptSeriesAndStr` - but a `Series` is valid too, and it needs to be Hashables only inside the ListLikes... what about `ListLikeExceptStrHashable = TypeVar("ListLikeExceptStrHashable", MutableSequence[Hashable], np.ndarray, tuple[Hashable], "Index")`
4. That doesn't work because `pd.Index(({1: 1, 2:2, 3:3}, {"test": "this"}))` is possible to construct, but errors when trying to use it as the `names` param for `read_csv`, because it's not hashable (gives a `TypeError: unhashable type: 'dict'`).

I could just exclude the `Index` option, but that seems like a shame. However, I don't think there's an easy way of type hinting 'it's an Index, and the elements in the Index are Hashable', but maybe I'm missing something.

If I had advice here on an acceptable type I'd happily provide a PR - I think allowing: MutableSequence[Hashable], np.ndarray, tuple[Hashable] would be an improvement over what we have now even if it's not perfect.

### PR DESCRIPTION
**Pull request by EFord36**
- [X] Closes #605, Closes #623
- [X] Tests added: Please use `assert_type()` to assert the type of any return value

Submitted as 1 PR for the 2 issues because the relevant code is so close that I thought it might be quicker to review together, plus trying to have both as separate PRs would likely result in merge conflicts if/when one was merged before the other. The commits addressing the two issues are separate though, so it would be easy for me to split into 2 separate PR if this is preferred.

As well as read_csv, modify read_table, read_clipboard, read_excel, which all have the relevant params (I searched for other functions but let me know if I missed any).

Closes #605 in a different way than suggested in that ticket, in order to allow broader types than just lists of string or ints, since list-likes are allowed here. Naming of the type alias UsecolsArgType was inspired by ColspaceArgType, happy to change if desired.

Please let me know if coverage of more different types for `names` and/or `usecols` is needed in the tests, or if there are stylistic details you would like me to change. There is a lot of repetition between the tests for the different functions that have these params - I'm happy to work on reducing it, but I thought it might mean restructuring some of the existing tests, so I didn't want to fiddle with it too much until I knew if it (and the actual functional change) was desired.

Passes tests (`poetry run poe test_all`) locally when the last commit before my changes is `7730abc` - the two commits after that (`6819e32` and `9c301b3`) result in test failures for me locally that seem unrelated to my change, and I get if I just run on `main` with no changes.

### CODE REVIEW

**Review by Dr-Irv — CHANGES_REQUESTED** [review]
Thanks for this nice PR and for combining the changes for both issues in the same PR, and the extensive tests.

I would like to add tests that make sure that a plain string is not accepted where it is not supposed to be.  Something like this:
```python
        if TYPE_CHECKING_INVALID_USAGE:
            pd.read_excel(path, names="foo")  # type: ignore[call-overload] # pyright: ignore[reportGeneralTypeIssues]
            pd.read_csv(path, usecols="foo")  # type: ignore[arg-type] # pyright: ignore[reportGeneralTypeIssues]
```
I tried the above, with your PR, and it worked, but you should add tests for the `names` and `usecols` argument where `str` is not accepted, and I think it is just for `names` for `read_excel()`.

I think that for `read_excel()` you use `call-overload`, but for the rest, `arg-type` should work.

**Comment by EFord36** [comment]
Added tests to make sure the plain string isn't accepted (and one for read_excel to check it is accepted where it should be).

Thanks for the guidance, it made adding the tests nice and quick for me!

Running the tests a few times, turns out it needs `arg-type` for `usecols`, but `call-overload` for `names`. I'm speculating maybe because `usecols` has a specific type alias that is shared between all the overloads, mypy is smart enough there to take into account that the argument type is the same between overloads, and raise `arg-type`, whereas for `usecols`, because the (still shared) type hint is now more complex, it doesn't? I may be missing something obvious, but to me it seems like the failures are for the same reason.

**Review by Dr-Irv — APPROVED** [review]
Thanks @EFord36 .  Nice work.

**Comment by Dr-Irv** [comment]
> (I'm speculating maybe because `usecols` has a specific type alias that is shared between all the overloads, mypy is smart enough there to take into account that the argument type is the same between overloads, and raise `arg-type`, whereas for `usecols`, because the still shared type hint is now more complex, it doesn't? I may be missing something obvious, but to me it seems like the failures are for the same reason.)

TBH, I've never figured out exactly why mypy picks one error over another.  So we put in the error that was reported to make sure that we get through CI.  For these kinds of tests where we are using `TYPE_CHECKING_INVALID_USAGE`, the goal is to make sure that mypy and pyright flag them as known errors.  The specific error reported is less of a concern.

**Pull request merged**
