### PR TITLE
for issue 429

### LINKED ISSUE #429: Nightly build appears to be broken

### PR DESCRIPTION
**Pull request by ramvikrams**
- [x] Closes #429 
- [ ] Tests added: Please use `assert_type()` to assert the type of any return value

### CODE REVIEW

**Review by Dr-Irv — CHANGES_REQUESTED** [review]
See here: https://github.com/pandas-dev/pandas-stubs/blob/97dfaa955a6197e828b76f313cb591f6c56ad404/tests/test_resampler.py#L304
for an example of how to use `pytest_warns_bounds`.  You need to specify the `upper` parameter

**Comment by ramvikrams** [comment]
> See here: https://github.com/pandas-dev/pandas-stubs/blob/97dfaa955a6197e828b76f313cb591f6c56ad404/tests/test_resampler.py#L304
> for an example of how to use `pytest_warns_bounds`.  You need to specify the `upper` parameter

Yes sir

**Comment by ramvikrams** [comment]
> > See here: https://github.com/pandas-dev/pandas-stubs/blob/97dfaa955a6197e828b76f313cb591f6c56ad404/tests/test_resampler.py#L304
> > 
> > for an example of how to use `pytest_warns_bounds`.  You need to specify the `upper` parameter
> 
> Yes sir

Still not getting the checks passed after adding upper

**Comment by Dr-Irv** [comment]
> Still not getting the checks passed after adding upper

Use `pytest_warns_bounds()` not `python_warns_bounds()`.  When checks fail, look at the results of the checks to see the error messages.

But before you push, you should test locally by running `poetry run poe test` to see if the tests pass on your machine

**Comment by ramvikrams** [comment]
> > Still not getting the checks passed after adding upper
> 
> Use `pytest_warns_bounds()` not `python_warns_bounds()`.  When checks fail, look at the results of the checks to see the error messages.
> 
> But before you push, you should test locally by running `poetry run poe test` to see if the tests pass on your machine

Yes sir

**Comment by ramvikrams** [comment]
It is still saying undefined name `pytest_warns_bounds`

**Comment by Dr-Irv** [comment]
> It is still saying undefined name `pytest_warns_bounds`

It means you didn't import it.  Look at other examples.  This is basic python programming.

**Comment by Dr-Irv** [comment]
> > > It is still saying undefined name `pytest_warns_bounds`
> > 
> > 
> > It means you didn't import it. Look at other examples. This is basic python programming.
> 
> Sir what is the module to import `pytest_warns_bounds` i coudn't find it.

Sorry it is `pytest_warns_bounded` not `pytest_warns_bounds`  .  Look at `test_frame.py` for an example

**Comment by ramvikrams** [comment]
Done sir

**Review by Dr-Irv — CHANGES_REQUESTED** [review]
You changed WAY too many tests.  Only change the ones listed in the original issue.

**Comment by ramvikrams** [comment]
> You changed WAY too many tests. Only change the ones listed in the original issue.

yes sir

**Comment by ramvikrams** [comment]
> You changed WAY too many tests. Only change the ones listed in the original issue.

Done sir

**Review by Dr-Irv — CHANGES_REQUESTED** [review]
This is trickier than I thought.  You have to look at the 6 failures in the nightly CI and we have to put in something where if the pandas  version is larger than the bound specified, we catch an exception rather than trap a warning.  I think the right solution is to modify the implementation of `pytest_warns_bounded` to return a different context manager if the version of pandas is >= the upper bound such that the context manager is trapping the exception.  Use `contextlib.supprress()` and you'd have to pass in the expected exception type.

This is non-trivial.  I'm not sure you will be able to do it.  If not, let me know, and I will take this over.

**Comment by ramvikrams** [comment]
> contextlib.supprress()

I think it would be better if you take over.

**Comment by Dr-Irv** [comment]
closing in favor of #436

**Comment by ramvikrams** [comment]
> closing in favor of #436

yes sir

**Pull request closed without merging**
