### PR TITLE
Remove use of removed mypy option

### PR DESCRIPTION
**Pull request by hauntsaninja**
I removed this in 0.981

### CODE REVIEW

**Comment by Dr-Irv** [comment]
So even without this change, we are now failing with `mypy` 0.981.  Tracking in #336

**Comment by twoertwein** [comment]
> So even without this change, we are now failing with `mypy` 0.981. Tracking in #336

I think it will take some time to be compatible with 0.981.

@hauntsaninja For now, it would be good to limit the mypy version in pyproject.toml. Making any change to pyproject.toml invalidates the cached poetry.lock file which in this case installs the new mypy and lets everything fail.

**Comment by Dr-Irv** [comment]
> @hauntsaninja For now, it would be good to limit the mypy version in pyproject.toml. Making any change to pyproject.toml invalidates the cached poetry.lock file which in this case installs the new mypy and lets everything fail.

Good idea

**Review by twoertwein — APPROVED** [review]

**Review by Dr-Irv — APPROVED** [review]
thanks @hauntsaninja

**Pull request merged**
