### PR TITLE
HDFStore.__iter__

### PR DESCRIPTION
**Pull request by twoertwein**
Without this PR

```py
for key in pd.HDFStore(...):
   ...
```
would cause `error: "List[str]" has no attribute "__next__"  [attr-defined]`

### CODE REVIEW

**Comment by twoertwein** [comment]
Enabled Y034 which in theory should have caught this (https://github.com/PyCQA/flake8-pyi/issues/348). Also added Self wherever Y034 was suggesting it (could be used in many more places). 

xref https://github.com/pandas-dev/pandas/issues/51233

**Review by Dr-Irv — APPROVED** [review]
Glad you found the `Y034` thing.  Thanks @twoertwein

**Comment by twoertwein** [comment]
The CI seems kind of slow (most runs are queued). Should we:

- only test on the latest and oldest python versions
- still test on all python versions but test them disjointly across different platforms
- same as above but always test oldest/newest on all platforms

**Comment by Dr-Irv** [comment]
> The CI seems kind of slow (most runs are queued). Should we:
> 
> * only test on the latest and oldest python versions
> * still test on all python versions but test them disjointly across different platforms
> * same as above but always test oldest/newest on all platforms

I think we should leave it as is.  It seems the runs being queued depends on time of day, and happens more with Windows and MacOS than Linux.

**Pull request merged**
