### PR TITLE
Experiment2

### PR DESCRIPTION
**Pull request by bashtage**
- [ ] Closes #xxxx (Replace xxxx with the Github issue number)
- [ ] Tests added: Please use `assert_type()` to assert the type of any return value

### CODE REVIEW

**Comment by Dr-Irv** [comment]
In this case, it failed because changing `pyproject.toml` caused it to use a different cache.  

So the issue now is that if we do update `pyproject.toml`, the cache is invalid and poetry figures out the dependencies again, and then something gets messed up.

**Comment by bashtage** [comment]
That is also my conclusion

**Comment by Dr-Irv** [comment]
> That is also my conclusion

One thing to try is to use `poetry use system` before each `poetry` command (especially before `poetry install`) which I think will force everything to get installed into the "system" environment, and avoid having a virtual environment.

**Comment by Dr-Irv** [comment]
> I think I tested disabling the poetry.lock caching but adding my local poetry.lock: it still failed (but maybe I'm misremembering something)
> 
> edit: tested it here [dfba485](https://github.com/pandas-dev/pandas-stubs/commit/dfba4857340984d5a0bcbf4ede1e49110de7c449)

It's the other way that is not working.  If the cache is invalid, then the CI is failing.

**Comment by twoertwein** [comment]
> It's the other way that is not working. If the cache is invalid, then the CI is failing.

In theory, my local poetry.lock should be the same as the cached poetry.lock. When disabled caching and adding my poetry.lock, it should have the same effect - but it would always be a cache hit.

**Comment by Dr-Irv** [comment]
> Trying to skip the cache on windows.

I tried that last night.  It doesn't solve the problem. 

 The issue here is that if there is no cache, it will fail.  If we do get the cache, then it succeeds.

So we need to know that when we have a new version of `pyproject.toml`, which would affect `poetry.lock`, and then when we do `poetry install`, it determines dependencies, places all the packages in the virtual env, but then when we do any other `poetry` command, it is not using the virtual environment.

**Comment by twoertwein** [comment]
Is there a way to download the cached poetry.lock so that we can compare it to a newly generated one?

**Comment by bashtage** [comment]
If you know the location could just cat them.

**Comment by twoertwein** [comment]
> If you know the location could just cat them.

Would just need to do `cat poetry.lock` after loading the caching.

**Comment by Dr-Irv** [comment]
> Is there a way to download the cached poetry.lock so that we can compare it to a newly generated one?

I don't think that it matters.  As soon as we update `pyproject.toml`, there will be no valid cached file, and we'll run into the  current problem, because the CI will create a new `poetry.lock` file.

**Comment by bashtage** [comment]
Should carefully check if any of the deps have changed from when it last
worked. Could be something else, like virtualenv.

**Comment by bashtage** [comment]
Pinning poethepoet to 0.16.0 (vs 0.16.1) fixes the problem.

**Comment by Dr-Irv** [comment]
> Pinning poethepoet to 0.16.0 (vs 0.16.1) fixes the problem.

Oooh. That's good news.  I will test in what I'm trying just to be sure.

**Comment by twoertwein** [comment]
It might be worth pinning all versions in pyproject.toml (and also the github action versions to their exact version). We will need to update them every now and then but we might be spared a few days of debugging :)

**Comment by bashtage** [comment]
Closing in favor of #249

**Comment by Dr-Irv** [comment]
Created https://github.com/nat-n/poethepoet/issues/88

**Pull request closed without merging**
