### PR TITLE
Use new nightly wheels' location

### LINKED ISSUE #726: Update nightly to use new location
The location of nightly builds for pandas is moving.  Once [this pandas issue](https://github.com/pandas-dev/pandas/pull/53341) is closed and the new upload procedure for pandas is working, we should update `scripts/test/run.py` to refer to the new location.

### PR DESCRIPTION
**Pull request by jarrodmillman**
- [x] Depends on https://github.com/pandas-dev/pandas/pull/53341
- [ ] Closes #726

### CODE REVIEW

**Review by Dr-Irv — COMMENTED** [review]
I'll merge this in once I see that the uploads for all of the platforms have worked for a night.  Can you put a note here when that has been done?

**Comment by jarrodmillman** [comment]
The PR was merged yesterday and it looks to me like everything worked:
- https://anaconda.org/scientific-python-nightly-wheels/pandas/files

You may want to take a quick look to make sure all the wheels you expect are there.

**Comment by Dr-Irv** [comment]
> @Dr-Irv The PR was merged yesterday and it looks to me like everything worked:
> 
> * https://anaconda.org/scientific-python-nightly-wheels/pandas/files
> 
> You may want to take a quick look to make sure all the wheels you expect are there. Let me know if there are any issues.

Looks good and I tested it on my laptop, so it's good to go.  Once PR Is green, I'll approve and merge. Thanks for the help.

**Review by Dr-Irv — APPROVED** [review]
Thanks @jarrodmillman

**Pull request merged**
