### PR TITLE
Fix nightly runs

### LINKED ISSUE #468: nightly failing - possibly due to pandas bug
nightly is failing due to arithmetic between offsets and period index changing result.  

So either we see if that gets fixed, or change our tests.

See https://github.com/pandas-dev/pandas/issues/50162

### PR DESCRIPTION
**Pull request by Dr-Irv**
- [x] Closes #468

Made changes to the tests to fix the current set of nightly run errors.

### CODE REVIEW

**Review by twoertwein — APPROVED** [review]
Does this also close #477?

**Comment by Dr-Irv** [comment]
> Does this also close #477?

yes

**Comment by Dr-Irv** [comment]
@twoertwein any reason not to merge?

**Comment by twoertwein** [comment]
Was waiting if @bashtage has comments

**Pull request merged**
