### PR TITLE
[Issue #461] Added timedelta as a diviser option for Timemedeltaseries

### LINKED ISSUE #461: Dividing a series of Timedeltas by a Timedelta is rejected
**Describe the bug**
Should allow `TimedeltaSeries / pd.Timedelta`

**To Reproduce**
```python
import pandas as pd

tds = pd.Series(pd.timedelta_range(start="1 day", periods=10))
td = pd.Timedelta("2 hours")

q = tds / td
```
pyright reports:
```text
tddiv.py
  c:\Code\pandas-stubs\tddiv.py:6:5 - error: Operator "/" not supported for types "TimedeltaSeries" and "Timedelta"
    Operator "/" not supported for types "TimedeltaSeries" and "Timedelta" (reportGeneralTypeIssues)
```

**Please complete the following information:**
 - OS:Windows 10
 - python version:  3.9
 - version of type checker:  pyright 1.1.283
 - version of installed `pandas-stubs`:  1.5.2.221124

**Additional context**

Just need to add `Timedelta` here:
https://github.com/pandas-dev/pandas-stubs/blob/58416f2c8d3dd44f60e0b2a89da1328ae3fbb58b/pandas-stubs/core/series.pyi#L1789

### PR DESCRIPTION
**Pull request by muddi900**
- [x] Closes #461(Replace xxxx with the Github issue number)
- [ ] Tests added: Please use `assert_type()` to assert the type of any return value

### CODE REVIEW

**Review by Dr-Irv — CHANGES_REQUESTED** [review]
1. Something you have done has messed up formatting.  Be sure to do `poetry run poe style` before you commit.
2.  Please add a test.  YOu can add it right after this line by just reversing the arguments:
https://github.com/pandas-dev/pandas-stubs/blob/58416f2c8d3dd44f60e0b2a89da1328ae3fbb58b/tests/test_scalars.py#L774

**Comment by Dr-Irv** [comment]
@muddi900 are you going to be able to finish this?

**Comment by muddi900** [comment]
Oh forgot about this. I'll write a test by the end of the week.

**Comment by muddi900** [comment]
So the original issue has already been closed in another PR(#488), so there would be no point in continuing this.

**Comment by Dr-Irv** [comment]
> So the original issue has already been closed in another PR(#488), so there would be no point in continuing this.

Thanks for picking that up.

**Pull request closed without merging**
