### PR TITLE
Fix 288 - Add 'cross' as option for MergeHow

### LINKED ISSUE #288: MergeHow does not support "cross" joins
**Describe the bug**
Performing a cross join with two dataframes with `df.merge(..., how="cross", ...)` creates a typing error `Type "Literal['cross']" cannot be assigned to type "MergeHow"

**To Reproduce**

#### Minimal example
```python
import pandas as pd

df1 = pd.DataFrame(data={"a": [1, 2, 3]})
df2 = pd.DataFrame(data={"b": ["x", "y", "z"]})

df3 = df1.merge(df2, how="cross")
```

#### Pyright

```
Found 1 source file
pyright 1.1.270
[...]
[...]/cross_merge.py:6:26 - error: Argument of type "Literal['cross']" cannot be assigned to parameter "how" of type "MergeHow" in function "merge"
    Type "Literal['cross']" cannot be assigned to type "MergeHow"
      "Literal['cross']" cannot be assigned to type "Literal['left']"
      "Literal['cross']" cannot be assigned to type "Literal['right']"
      "Literal['cross']" cannot be assigned to type "Literal['outer']"
      "Literal['cross']" cannot be assigned to type "Literal['inner']" 
```

**Please complete the following information:**
 - OS: MacOS
 - OS Version: 12.5.1
 - python version: 3.10.5
 - version of type checker: `pyright 1.1.270`
 - version of installed `pandas-stubs`: `1.4.4.220906`

**Additional context**
[L231: _typing.pyi](https://github.com/pandas-dev/pandas-stubs/blob/0a5a4be30b8655757e0188c4c558f379eff728c9/pandas-stubs/_typing.pyi#L231) 

[pandas DataFrame.merge docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html) - describes `how="cross"` option.

### PR DESCRIPTION
**Pull request by alexc-yellowcanary**
- [x] Closes #288 (Replace xxxx with the Github issue number)
- [x] Tests added: Please use `assert_type()` to assert the type of any return value
---

- Add 'cross' as potential value for `MergeHow`
- Add test for `how=cross` (fails without patch)

### CODE REVIEW

**Comment by Dr-Irv** [comment]
The test you added is fine.  However, I was surprised that this PR was needed, as I had just recently used `cross` in my own code, and the type checkers didn't report an error.  Turns out that `pd.merge()` types `how` as `str`, so would you mind making the change there as well to have it use `MergeHow` as the type, and then add a similar test?

**Comment by alexc-yellowcanary** [comment]
PR for `pandas`: https://github.com/pandas-dev/pandas/pull/48513

**Comment by bashtage** [comment]
This fix here isn't 100% correct. Need distinct joinhow and megehow types since the 4 core values are widely used, and cross is only for merge.

**Comment by bashtage** [comment]
Test is now in #355

**Comment by Dr-Irv** [comment]
Closed in favor of #355

**Pull request closed without merging**
