### PR TITLE
TYP: de-duplicate some type unions

### PR DESCRIPTION
**Pull request by twoertwein**
This will avoid the new behavior/regression in mypy 0.981https://github.com/python/mypy/issues/13760

### CODE REVIEW

**Comment by bashtage** [comment]
Lgtm.

**Comment by twoertwein** [comment]
Should have maybe waited for more consensus on the mypy issue, luckily easy to revert :)

**Comment by twoertwein** [comment]
Might also consider skipping flake8-pyi's check for `int | float | complex`. Personally, I would like to avoid redundant unions, but they serve also a documentation pupose for which it might be more explicit to keep redundant unions.

**Comment by Dr-Irv** [comment]
> Might also consider skipping flake8-pyi's check for `int | float | complex`. Personally, I would like to avoid redundant unions, but they serve also a documentation pupose for which it might be more explicit to keep redundant unions.

I'm in favor of the redundancy, because it helps people understand what arguments are possible.  Trying to help the novices, not just the experts like us!

**Comment by bashtage** [comment]
I also prefer redundancy, esp for int | float.

**Comment by twoertwein** [comment]
Opened #342 to revert the change and disable the flake8-pyi check. Also opened a PR for the few pyi files in pandas itself.

**Comment by AlexWaygood** [comment]
(flake8-pyi maintainer here)

In case it's helpful: we deliberately excluded type aliases from Y041 on the grounds that redundant unions often serve valuable documentation purposes. So flake8-pyi will complain about this code:

```python 
x: int | float
```

But it _deliberately won't_ complain about this code:

```python 
from typing_extensions import TypeAlias
_IntOrFloat: TypeAlias = int | float
x: _IntOrFloat
```

**Comment by twoertwein** [comment]
> But it _deliberately won't_ complain about this code:

I think it did that manually :)

**Pull request merged**
