### PR TITLE
 Setup optional CI jobs using pyright strict mode

### PR DESCRIPTION
**Pull request by JanEricNitschke**
Setup a optional CI job that uses full pyright strict mode by taking its settings from `pyrightconfig-strict.json`.

Addresses the other points made here: https://github.com/pandas-dev/pandas-stubs/issues/952

### CODE REVIEW

**Comment by JanEricNitschke** [comment]
Did a test run here: https://github.com/JanEricNitschke/pandas-stubs/actions/runs/9726191446/job/26844350295

**Review by Dr-Irv — APPROVED** [review]
thanks @JanEricNitschke 

It looks like there is a LOT of work to do to make the stubs work in strict mode.

**Comment by JanEricNitschke** [comment]
Yeah, it is mostly missing type hints or type parameters. Would it make sense to enable the pyright_strict test also in PRs, currently i made it like the others where it only runs on commits to main and not on PR creation like the other optionals.

Might make sense to also have it run here to see the number of errors getting lower on changes?

**Comment by Dr-Irv** [comment]
> Yeah, it is mostly missing type hints or type parameters. Would it make sense to enable the pyright_strict test also in PRs, currently i made it like the others where it only runs on commits to main and not on PR creation like the other optionals.
> 
> Might make sense to also have it run here to see the number of errors getting lower on changes?

I'm hesitant to do that, because then every PR will show a failure, which can be confusing to contributors.

**Pull request merged**
