### PR TITLE
GH1006 Update workflows version 

### LINKED ISSUE #1006: Update workflows actions to remove Node deprecation warning
**Describe the bug**
Deprecation warnings showing up as we run Github Actions workflow.

image

Github Actions

### PR DESCRIPTION
**Pull request by loicdiridollou**
- [x] Closes #1006 
- [x] Tests added: Please use `assert_type()` to assert the type of any return value

### CODE REVIEW

**Review by twoertwein — APPROVED** [review]
Happy to merge but I would like to first test that the three "magic" comments still work :)

**Comment by loicdiridollou** [comment]
image
They all ran well when triggered (I had set them up to already used the node20 versions of the actions).

**Comment by twoertwein** [comment]
Thank you @loicdiridollou !

**Pull request merged**
