### PR TITLE
CI: ignore warnings from pandas-nightly

### LINKED ISSUE #666: nightly failures as of 4/29/2023, 10:15PM EST
See https://github.com/pandas-dev/pandas-stubs/actions/runs/4841786968/jobs/8628302624

- Have to remove `pytest_warns_bounded` in `test_frame.py:test_types_groupby()`
- Have to remove `pytest_warns_bounded` in `test_frame.py:test_groupby_applyl()`
- Have to add `pytest_warns_bounded` in `test_styler.py:test_applymap()`
- Have to add `pytest_warns_bounded` in `test_styler.py:test_applymap_index()`

### PR DESCRIPTION
**Pull request by twoertwein**
closes #666

`pytest_warns_bounded` becomes unused with this PR

### CODE REVIEW

**Comment by Dr-Irv** [comment]
OK, I tried this and it worked, so let's use this going forward.  Can you convert it from Draft?

**Comment by twoertwein** [comment]
Could also remove `pytest_warns_bounded`?

Unrelated: could replace flake8 & flake8-pyi & pyupgrade with ruff, would speed up pre-commit and pandas did the same. Could also replace isort (pandas didn't do that as ruff doesn't support cython).

**Review by Dr-Irv — APPROVED** [review]
thanks @twoertwein

**Comment by Dr-Irv** [comment]
> Could also remove `pytest_warns_bounded`?

We might need it if there are deprecation warnings in a current release that we are willing to tolerate.
> 
> Unrelated: could replace flake8 & flake8-pyi & pyupgrade with ruff, would speed up pre-commit and pandas did the same. Could also replace isort (pandas didn't do that as ruff doesn't support cython).

I'm not familiar with ruff, but would like to keep isort.  Open to having you do a PR.

**Pull request merged**
