### PR TITLE
Support mypy 1.1.1 and pyright 1.1.300

### PR DESCRIPTION
**Pull request by Dr-Irv**
Updating `mypy` and `pyright` versions.  Required a change to a test that `pyright` now correctly picks up.

### CODE REVIEW

**Review by twoertwein — APPROVED** [review]
Great that more and more of the negative tests are working as expected :)

**Comment by twoertwein** [comment]
(pandas) nightly seems to be failing again:

>  FAILED tests/test_frame.py::test_types_window - FutureWarning: Support for axis=1 in DataFrame.expanding is deprecated and will be removed in a future version. Use obj.T.expanding(...) instead
> FAILED tests/test_series.py::test_types_window - FutureWarning: The 'axis' keyword in Series.expanding is deprecated and will be removed in a future version. Call the method without the axis keyword instead.
> FAILED tests/test_series.py::test_types_ewm - FutureWarning: The 'axis' keyword in Series.ewm is deprecated and will be removed in a future version. Call the method without the axis keyword instead.

**Comment by Dr-Irv** [comment]
> (pandas) nightly seems to be failing again:
> 
> > FAILED tests/test_frame.py::test_types_window - FutureWarning: Support for axis=1 in DataFrame.expanding is deprecated and will be removed in a future version. Use obj.T.expanding(...) instead
> > FAILED tests/test_series.py::test_types_window - FutureWarning: The 'axis' keyword in Series.expanding is deprecated and will be removed in a future version. Call the method without the axis keyword instead.
> > FAILED tests/test_series.py::test_types_ewm - FutureWarning: The 'axis' keyword in Series.ewm is deprecated and will be removed in a future version. Call the method without the axis keyword instead.

So the question here is whether we make those changes now (because nightly is post 2.0), or wait until we start supporting 2.0, which is soon to be released.  Opinion?

**Comment by twoertwein** [comment]
I think in the past we removed arguments when the currently released pandas emits warnings about the usage. In the current case, not even 2.0 emits a warning (didn't test it) so I'm not sure what the best way forward is.

Generally, I'm always happy to remove "soon"-to-be deprecated arguments as it makes the annotations and testing easier :) If we want to stick with the current "policy", we should guard these tests behind a pandas<2.1.

**Comment by Dr-Irv** [comment]
> Generally, I'm always happy to remove "soon"-to-be deprecated arguments as it makes the annotations and testing easier :) If we want to stick with the current "policy", we should guard these tests behind a pandas<2.1.

I think that's the best solution.  Once 2.0 is released, and we start fixing the stubs with all the 2.0 features, we will remove the test code and tests for pandas <= 1.5, so this mirrors that practice.

**Pull request merged**
