### PR TITLE
Fix SQL parameter type

### PR DESCRIPTION
**Pull request by Tolker-KU**
Align parameter type to SQL functions: https://github.com/pandas-dev/pandas/blob/main/pandas/io/sql.py#L370
- [ ] Closes #xxxx (Replace xxxx with the Github issue number)
- [ ] Tests added: Please use `assert_type()` to assert the type of any return value

### CODE REVIEW

**Review by Dr-Irv — CHANGES_REQUESTED** [review]
Can you add a test that illustrates why this is needed, i.e., why the current types for the `params` argument don't work?

**Comment by Tolker-KU** [comment]
Hi!

Thanks for getting back quickly! I'm not quite sure how to test this change. Eventually we are calling into SQLAlchemy when using these methods - and SQLAlchemy types the parameters as `Any`. This is the reasoning behind the change

**Comment by Dr-Irv** [comment]
> Hi!
> 
> Thanks for getting back quickly! I'm not quite sure how to test this change. Eventually we are calling into SQLAlchemy when using these methods - and SQLAlchemy types the parameters as `Any`. This is the reasoning behind the change

If you look at `tests/test_io.py`, and search for `read_sql_query()`, you will want to add a test similar to one of those, using example code that currently fails with the stubs, but would work with your change.

**Review by Dr-Irv — CHANGES_REQUESTED** [review]
In thinking about this, I think the `Any` type is too wide.  For example, you couldn't pass an instance of any class as a parameter to an SQL call, it would have to be some kind of scalar.  So can you change the places where you used `Any` in this PR to use `Scalar` instead, which you can import from `pandas._typing` ?

**Comment by Tolker-KU** [comment]
Sounds like a good solution to me. I've made the change

**Review by Dr-Irv — APPROVED** [review]
Thanks @Tolker-KU

**Pull request merged**
